apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/vrtexe/homelab-gitops.git
      targetRevision: HEAD
      path: apps/crossplane
      ref: repo
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 2.3.3
      helm:
        valueFiles:
          - $repo/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
