apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.crossplane.io/stable
      chart: crossplane
      targetRevision: 2.3.3
      path: .
      helm:
        valueFiles:
          - $argocd.source.path/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
