apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-envoy-gateway
  namespace: argocd
spec:
  project: default
  source:
    path: .
    repoURL: oci://docker.io/envoyproxy/gateway-helm
    targetRevision: v1.8.3
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
